use_frameworks!

platform :ios, '11.0'

target 'CPTPhotoMontageView_Example' do
  pod 'CPTPhotoMontageView', :path => '../'

  target 'CPTPhotoMontageView_Tests' do
    inherit! :search_paths

    
  end
end
